server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
            - id: workspace-service-route
              uri: lb://workspace-service
              predicates:
                - Path=/api/v1/workspaces/**,/api/v1/spaces/**,/api/v1/tasks/**,/api/v1/sprints/**
            - id: ai-service-route
              uri: lb://ai-service
              predicates:
                - Path=/api/v1/ai/**
            - id: notification-service-route
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**

eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 2
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
